### PR TITLE
Feature/milestone 1

### PR DESCRIPTION
**Pull request by MrSayyod**
Due to requirements:
- created a new repository;
- followed the GitFlow guidelines.
- created 4 feature branches for each milestone;
- set up code linters;
- set `development` branch as a default;
- created empty lib directory for the logic of the game;
- created bin directory with executable file;

### CODE REVIEW

**Comment by MrSayyod** [comment]
My partner had an electricity problem. Therefore all changes were committed only by me.

**Comment by MrSayyod** [comment]
Cannot fix Stickler error:
`Lint/ScriptPermission: Script file main.rb doesn't have execute permission`
chmod 755 main.rb => DONE
chmod --cache false => shows `no offenses detected`

**Comment by MrSayyod** [comment]
rubocop.yml file was changed to fix stickler error:
added this line
```
Lint/ScriptPermission:
  Enabled: False
```

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Hi Team,
## Great work. Congratulation :+1: Approved.
Go ahead and merge to develop.
_Goodluck in your next milestone_ *Happy coding*

**Pull request merged**
