### PR TITLE
Game logic

### PR DESCRIPTION
**Pull request by MrSayyod**
Due to requirements:

- followed the GitFlow guidelines;
- branch name renamed into `game_logic`
- created content for the game;
- `main.rb` file is responsible for user interaction;
- used `attr_readers` and `attr_writers`;
- the code does not allow to perform invalid action.

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
## Status:: Require changes❌.
# 👋 Team,
Your application is quite robust. Your methods are well split your code looks clean and easy to read. The game also works fine but there are a few tweaks we can make to make it more robust.
* [x] Currently player_name either player_1 or player_2 can be empty. Player name should accept a value ideally a combination of alphabets

**[ OPTIONAL BUT RELEVANT IN MY OPINION]**
* [x] Let us allow players to determine whether or not they want to end the game after a win or a draw rather than having the game ended abruptly after a result is reached.
You may even go the extra mile to keep track of victory count
# That is it, kindly make this change and submit the project for review🦸‍♂️
#### Happy coding💻
Addo

**Comment by MrSayyod** [comment]
- the player's name is able to accept an empty value.
- after  ending the game, players will be offered an option to play the game again

**Review by stratospherique — APPROVED** [review]
### Great work implementing the suggested changes :clap: :clap: Congrats, the project is approved :heavy_check_mark: You may merge :+1: :+1: :+1: 

Keep up the good work :muscle: 
**_Ahmed Mahfoudh_**

###### PS: You misunderstood the point that the previous TSE was trying to make about the players' name. He requested that the game shouldn't accept empty names for players. :pray: fix that before merging.

**Comment by MrSayyod** [comment]
> ### Great work implementing the suggested changes 👏 👏 Congrats, the project is approved ✔️ You may merge 👍 👍 👍
> Keep up the good work 💪
> **_Ahmed Mahfoudh_**
> 
> ###### PS: You misunderstood the point that the previous TSE was trying to make about the players' name. He requested that the game shouldn't accept empty names for players. 🙏 fix that before merging.

Fixed! Thanks for the review!

**Pull request merged**
